[CI]: fix wrong path on windows runners
Tests were updated to prevent edge cases where mkdtemp() returns "short"
DOS paths on Windows, which cause errors like the following:

File "src\black\__init__.py", line 616, in main
  File "src\black\__init__.py", line 703, in get_sources
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpc6klofvk_pre_commit_vauxoo\\module_autofix1\\__init__.py'
does not start with 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\tmpc6klofvk_pre_commit_vauxoo